const checkLength = (string) => {
    const result = `${string} er ${string.length} bogstaver langt`;
    console.log(result);
}

checkLength("Halli Hallo");

const dataObject = {
    firstname: "Christian",
    lastname: "Sørensen",
    email: "chso5@elev.techcollege.dk",
    address: "Øster Uttrup Vej 1",
    postal: 9000
}

console.log(dataObject);


const changeKeyValue = (object, key, value) => {
    const changedObject = object[key] = value;
    console.log(changedObject);
}

changeKeyValue(dataObject, "address", "Øster Uttrup Vej 2");

const checkKeyValues = (object) => {
    let values = Object.keys(object);
    values.map((value) => {
        console.log(typeof object[value]);
    })
}

checkKeyValues(dataObject);

const container = document.getElementById("generator-container");
const gridContainer = document.querySelector(".grid-container");

const generateElement = (tag, text, background, className, id, container) => {
    const element = document.createElement(`${tag}`);
    element.innerHTML = `${text}`;
    element.style.background = `${background}`
    element.classList.add(`${className}`);
    element.id = `${id}`;

    container.appendChild(element);
}

generateElement("h1", "Generated by js", "Blue", "h1-header", "important-header", container);

//Opgave 6
const randBackground = () => {
    return Math.floor(Math.random() * 256);
  };

const divs = ["Div One", "Div Two", "Div Three", "Div Four", "Div Five", "Div Six", "Div Seven", "Div Eight", "Div Nine"];
divs.forEach((div) => {
    generateElement("div", `<p>${div}</p>`, `rgb(${randBackground()}, ${randBackground()}, ${randBackground()})`, "div-box", "div-box", gridContainer);
});